[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "2nXbNz4c1Rv6ba9jJucNWgTTuNbYGZYYRhE6MnoLc17v"

[programs.devnet]
oft = "2nXbNz4c1Rv6ba9jJucNWgTTuNbYGZYYRhE6MnoLc17v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./junk-id.json"

[scripts]
test = "~/.cargo/bin/anchor test --skip-deploy"
