[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "9jpCuRru6RpBBXSZQcpSnw9WT347up5fFLvLZrRfznih"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/main-user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
