[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "Eatvyksra7sosFDrfsgbqYPbQz8nTXXJ8GXG2spFS2Nn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/main-user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
